AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run a static website application deployed with Apache Web Server
   
Resources:     
  KittensCarouselStaticWebsiteCFInstance:  #instance'a ismi biz veriyoruz
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0c94855ba95c71c99    #EC2 "create instance" bölümünden alıyoruz
      InstanceType: t2.micro
      KeyName: HK-Virginia1   #pem dosya ismimiz
      SecurityGroups:
        - launch-wizard-1      #security groupsdan aldık (HTTP ve SSH açık olacak şekilde olmalı)
      Tags:
        - Key: Name
          Value: ApacheWebEC2  #instance'a ismi biz veriyoruz
      UserData: 
        Fn::Base64:
          !Sub |
            #! /bin/bash
            yum update -y
            yum install -y httpd
            DATE_TIME=`date`
            cd /var/www/html
            wget https://github.com/ibrahimkaratas88/clarusway-aws-devops-workshop/blob/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
            wget https://github.com/ibrahimkaratas88/clarusway-aws-devops-workshop/blob/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
            wget https://github.com/ibrahimkaratas88/clarusway-aws-devops-workshop/blob/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
            wget https://github.com/ibrahimkaratas88/clarusway-aws-devops-workshop/blob/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
            systemctl start httpd
            systemctl enable httpd
Outputs:
  InstanceId:
    Description: InstanceId of the first EC2 instance
    Value: !Ref KittensCarouselStaticWebsiteCFInstance
  PublicDNS:
    Description: Public DNS Name of the EC2 instance
    Value: !GetAtt 
      - KittensCarouselStaticWebsiteCFInstance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt 
      - KittensCarouselStaticWebsiteCFInstance
      - PublicIp